title: Railconcept

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed



#Actualités

collections:
  Actualite:
       output: true
       permalink: /:collection/:year/:month/:slug/