title: Rail Concept
url: https://www.railconcept.fr

plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - .well-known/

exclude:
  - api/bin/
  - api/obj/

highlighter: rouge
markdown: kramdown
timezone: Europe/Paris
kramdown:
  input: GFM

collections:
  catnews:
    output: true
    permalink: /catnews/:path/
  odt:
    output: true
    permalink: /odt/:path/
  nos_realisations:
    output: true
    permalink: /nos_realisations/:path/
  jobs:
    output: true
    permalink: /en/jobs/:path/
  news:
    output: true
    permalink: /en/news/:path/
  achievements:
    output: true
    permalink: /en/achievements/:path/
