title: Railconcept

# Build settings
theme: minima
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag


highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

collections:
  catnews:
    output: true
    permalink: /newstags/:path/
  odt:
    output: true
    permalink: /odt/:path/