title: Railconcept


collections:
  railconcept:
       output: true
       permalink: /:collection/:year/:month/:slug/
       

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed



