title: Railconcept

# Build settings
theme: minima
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

collections:
  catnews:
    output: true
    permalink: /catnews/:path/
  odt:
    output: true
    permalink: /odt/:path/
  newspost:
    output: true
    permalink: /newspost/:path/