title: Railconcept


# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown

plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate



collections:
  actualites:
    output: true
    permalink: /:collection/:year/:month/:day/:slug

# Front Matter Defaults
defaults:
  # _actualites
  - scope:
      path: "_actualites"
      type: posts
    values:
      layout: head
      read_time: true

