title: Rail Concept
url: https://www.railconcept.fr

plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - .well-known/

exclude:
  - api/bin/
  - api/obj/
  - pages/en/

highlighter: rouge
markdown: kramdown
timezone: Europe/Paris
kramdown:
  input: GFM

defaults:
  - 
    scope:
      path: "admin/**"
    values:
      sitemap: false
  - 
    scope:
      path: "assets/**"
    values:
      sitemap: false
  - 
    scope:
      path: "odt/**"
      type: "odt"
    values:
      sitemap: false
  - 
    scope:
      path: "catnews/**"
      type: "catnews"
    values:
      sitemap: false

collections:
  posts:
    output: true
    permalink: /actualites/:year-:month-:day-:title/
  catnews:
    output: true
    permalink: /catnews/:title/
    sitemap: false
  odt:
    output: true
    permalink: /odt/:title/
    sitemap: false
  nos_realisations:
    output: true
    permalink: /nos_realisations/:title/


navlinks:
  -
    href: "/qui-sommes-nous"
    label: "Nous Connaître"
  -
    href: "/competences"
    label: "Nos Compétences"
  -
    href: "/nos_realisations"
    label: "Nos Réalisations"
  -
    href: "/rejoignez-nous"
    label: "Carrières"
  -
    href: "/actualites"
    label: "Actualités"
  -
    href: "https://www.raillab.fr"
    label: "RailLab"
  -
    href: "/contact"
    label: "Contact"
    

#  jobs:
#    output: true
#    permalink: /en/jobs/:path/
#  news:
#    output: true
#    permalink: /en/news/:path/
#  achievements:
#    output: true
#    permalink: /en/achievements/:path/
