title: Railconcept
siteurl: https://railconcept.fr

plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

collections:
  catnews:
    output: true
    permalink: /catnews/:path/
  odt:
    output: true
    permalink: /odt/:path/
  nos-realisations:
    output: true
    permalink: /nos-realisations/:path/
  jobs:
    output: true
    permalink: /en/jobs/:path/
  news:
    output: true
    permalink: /en/news/:path/
  achievements:
    output: true
    permalink: /en/achievements/:path/