seo:
  facebook: "https://facebook.com"
  linkedin: "https://fr.linkedin.com/company/railconcept"
  location:
    country: France
    region: 30133 Les Angles
    street_adress: 2 Allée de la Tramontane
  tel: "+33490905485"
  tel_display: 04 90 90 54 85
  website_desc: Rail Concept, la référence des études ferroviaires amont
  website_desc_eng: Rail Concept, the reference in railways research studies
