seo:
  facebook: 'https://facebook.com'
  linkedin: 'https://linked.com'
  location:
    country: France
    region: 30133 Les Angles
    street_adress: 2 Allée de la Tramontane
  tel: '+33490905485'
  tel_display: 04 90 90 54 85
  website_desc: website description
  website_desc_eng: website description  english
