backend: 
  name: github
  repo: railconcept/railconcept

media_folder : assets/img/uploads

collections:
 - name: "website-settings"
   label:  "Website settings"
   files:
    - label: "Website settings"
      name: "site"
      file: "_data/site.yml"
      fields:
       - label: "Tel"
         name: "tel"
         widget: "string"
       - label: "Tel display"
         name: "tel_display"
         widget: "string"
       - label: "SEO"
         name: "seo"
         widget: "object"
         fields:
          - label: "Website description"
            name: "tagline"
            widget: "string"
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Street adress"
                name: "street_adress"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
              - label: "Country"
                name: "country"
                widget: "string"    

 - name: "actualites"
   label:  "Actualités"
   folder: "_actualites"
   create: true
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   fields:      
      - {label: "UID", name: "uid", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Profile picture", name: "image", widget: "image"}
      - {label: "Website", name: "url", widget: "string"}
      - {label: "Bio", name: "bio", widget: "string"}
      - {label: "Social Urls", name: "social", widget: "list"}
