backend: 
  name: github
  repo: a-issaoui/railconcept

media_folder : /img/uploads

collections:
  - name: "website-settings"
    label:  "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"