backend: 
  name: github
  repo: railconcept/railconcept

media_folder : assets/img/uploads

collections:
  - label: "website settings"
    name: "website_settings"
    files:
     - label: "Géneral settings"
       name: "general_settings"
       file: "_data/website_settings.yml"
       fields:
        - label: "Tags"
          name: "tags"
          widget: "select"
          multiple: true
          options: ["Design", "UX", "Dev"]
          default: ["Design"]